const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

const shell = (title, body, script = "") => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escapeHtml(title)} · BiteCode</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#17221d;background:#eef5f0}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 90% 0,#c9f3dc 0,transparent 30%),#eef5f0}.nav{height:68px;padding:0 max(22px,5vw);display:flex;align-items:center;justify-content:space-between;background:#ffffffdf;border-bottom:1px solid #d4e0d8}.brand{font-size:21px;font-weight:900;color:#15573b}.badge{background:#dcf5e6;color:#17603f;border-radius:99px;padding:7px 10px;font-size:12px;font-weight:800}.wrap{width:min(1120px,93vw);margin:34px auto}.card{background:#fff;border:1px solid #d5e0d8;border-radius:22px;padding:26px;box-shadow:0 18px 45px #19422c12}.hero{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:24px}h1{font-size:clamp(34px,5vw,58px);line-height:1;letter-spacing:-.045em;margin:10px 0}h2{margin:0 0 16px}.eyebrow{font-size:12px;font-weight:850;letter-spacing:.12em;text-transform:uppercase;color:#21815a}p{line-height:1.6;color:#56635c}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.field{margin-bottom:15px}label{font-size:13px;font-weight:800;display:block;margin-bottom:6px}input,textarea,select{width:100%;font:inherit;padding:11px 12px;border:1px solid #c6d4ca;border-radius:11px;background:#fcfdfc}textarea{min-height:92px;resize:vertical}.wide{grid-column:1/-1}.check{display:flex;gap:10px}.check input{width:auto;margin-top:3px}.btn{border:0;border-radius:11px;padding:12px 17px;background:#176f4a;color:#fff;font-weight:850;cursor:pointer}.btn.secondary{background:#e2f3e8;color:#175f40}.notice{margin-top:16px;padding:14px;border-radius:12px;background:#edf8f1;overflow-wrap:anywhere}.error{background:#fff0f0;color:#8e2730}.links a{display:block;color:#176f4a;margin:8px 0}.modal{position:fixed;inset:0;background:#10251bbd;display:grid;place-items:center;padding:20px;z-index:5}.modal-card{width:min(680px,95vw);max-height:90vh;overflow:auto;background:white;border-radius:22px;padding:28px}.modal ul{line-height:1.6;color:#46534c}.hidden{display:none}.result pre{white-space:pre-wrap;background:#f4f7f5;border-radius:12px;padding:15px;max-height:450px;overflow:auto}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.hero{display:block}}
</style></head><body><nav class="nav"><div class="brand">BiteCode AI Mentor</div><span class="badge">Demo administration</span></nav><main class="wrap">${body}</main><script>${script}</script></body></html>`;

export function lockedPage() {
  return shell("Admin link required", `<section class="card" style="max-width:650px;margin:70px auto;text-align:center"><div class="eyebrow">Protected administration</div><h1 style="font-size:45px">Admin link required</h1><p>Generate a short-lived administration link with the BiteCode demo CLI. Direct access cannot configure or launch mentor sessions.</p></section>`);
}

export function setupPage(defaults = {}) {
  const value = (key) => escapeHtml(defaults[key] ?? "");
  const levelOptions = ["Beginner", "Intermediate", "Advanced"].map((level) => `<option${defaults.knowledgelevel === level ? " selected" : ""}>${level}</option>`).join("");
  return shell("Scenario builder", `<div class="hero"><div><div class="eyebrow">AI Mentor demo</div><h1>Configure a mentor scenario.</h1><p>Adjust the predefined learning parameters, then generate a protected tester link.</p></div></div>
<form id="scenario" class="card"><h2>Tester</h2><div class="grid"><div class="field wide"><label>Tester name</label><input name="testerName" maxlength="100" required value="${value("testerName")}"></div></div>
<h2>Learning scenario</h2><div class="grid">
<div class="field"><label>Learner first name</label><input name="userfirstname" maxlength="100" required value="${value("userfirstname")}"></div>
<div class="field"><label>Knowledge level</label><select name="knowledgelevel">${levelOptions}</select></div>
<div class="field"><label>Course name</label><input name="coursename" maxlength="200" required value="${value("coursename")}"></div>
<div class="field"><label>Lesson name</label><input name="lessonname" maxlength="200" required value="${value("lessonname")}"></div>
<div class="field wide"><label>Lesson goal</label><textarea name="lessongoal" maxlength="2000" required>${value("lessongoal")}</textarea></div>
<div class="field wide"><label>Lesson content</label><textarea name="content" maxlength="12000" required>${value("content")}</textarea></div>
<div class="field"><label>Knowledge domain</label><textarea name="knowledgedomain" maxlength="1000">${value("knowledgedomain")}</textarea></div>
<div class="field"><label>Learner preferences</label><textarea name="userpreferences" maxlength="1500">${value("userpreferences")}</textarea></div>
<div class="field"><label>Learning memory (JSON)</label><textarea name="learningmemory" maxlength="5000">${value("learningmemory")}</textarea></div>
<div class="field"><label>Strengths (JSON)</label><textarea name="knowledgestrengths" maxlength="3000">${value("knowledgestrengths")}</textarea></div>
<div class="field"><label>Knowledge gaps (JSON)</label><textarea name="knowledgegaps" maxlength="3000">${value("knowledgegaps")}</textarea></div>
<div class="field"><label>Practice recommendations (JSON)</label><textarea name="practicerecommendations" maxlength="3000">${value("practicerecommendations")}</textarea></div>
<div class="field wide"><label>Internal scenario notes</label><textarea name="scenarioNotes" maxlength="2000">${value("scenarioNotes")}</textarea></div></div>
<div class="check field"><input id="adminConsent" name="adminConsent" type="checkbox" required><label for="adminConsent">I have consent to run this voice test and review its completion data.</label></div><button class="btn">Generate tester link</button><div id="output"></div></form>
<div id="info" class="modal"><section class="modal-card"><div class="eyebrow">Before you configure a test</div><h2>About this demo</h2><ul><li>The form is filled from the default scenario configuration and can be changed for each test.</li><li>No production learner or subscription is created or modified.</li><li>Daily usage and learner-history updates are bypassed for signed demo sessions.</li><li>The tester must accept a separate notice before microphone access begins.</li><li>Completion details are sent to the privately configured administrator address.</li><li>Do not enter secrets or unnecessary personal information.</li></ul><div class="check field"><input id="understand" type="checkbox"><label for="understand">I understand how this testing tool works.</label></div><button class="btn" id="continue" disabled>Continue to scenario builder</button></section></div>`, `
const modal=document.querySelector('#info'),understand=document.querySelector('#understand'),continueButton=document.querySelector('#continue'),form=document.querySelector('#scenario'),output=document.querySelector('#output');understand.onchange=()=>continueButton.disabled=!understand.checked;continueButton.onclick=()=>modal.classList.add('hidden');
form.onsubmit=async(event)=>{event.preventDefault();output.innerHTML='<div class="notice">Validating and signing the demo scenario…</div>';const payload=Object.fromEntries(new FormData(form));payload.adminConsent=payload.adminConsent==='on';try{const response=await fetch('/api/scenarios',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to create scenario');output.innerHTML='<div class="notice links"><strong>Tester link ready</strong><a target="_blank" rel="noreferrer" href="'+data.testerUrl+'">Open demo</a><button type="button" class="btn secondary" id="copy">Copy tester link</button><a target="_blank" rel="noreferrer" href="'+data.resultUrl+'">Open result page</a><div>Expires: '+new Date(data.expiresAt).toLocaleString()+'</div></div>';document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(data.testerUrl)}catch(error){output.innerHTML='<div class="notice error">'+escapeText(error.message)+'</div>'}};function escapeText(value){const element=document.createElement('div');element.textContent=value;return element.innerHTML}`);
}

export function resultPage(session) {
  const visible = { id: session.id, status: session.status, testerName: session.testerName, scenario: session.scenario, createdAt: session.createdAt, activatedAt: session.activatedAt, testerConsentAcceptedAt: session.testerConsentAcceptedAt, completedAt: session.completedAt, result: session.result ?? null, notification: session.notification ?? null };
  return shell("Demo result", `<section class="card result"><div class="eyebrow">Administrator result</div><h1 style="font-size:43px">${escapeHtml(session.scenario?.lessonname || "AI Mentor demo")}</h1><p>Status: <strong>${escapeHtml(session.status)}</strong></p><pre>${escapeHtml(JSON.stringify(visible, null, 2))}</pre></section>`);
}

export function errorPage(message) { return shell("Unavailable", `<section class="card" style="max-width:620px;margin:70px auto;text-align:center"><h1 style="font-size:42px">Link unavailable</h1><p>${escapeHtml(message)}</p></section>`); }
